### ISSUE TITLE
Comments issue

### ISSUE THREAD

**Issue by AndeeOwL** [krisitown/pathfinder#1]
Здравей ето проекта да видиш проблема е че коментарите на първия Article работят но на всеки следващ не работи, Лъчо каза че трябва да подавам articleId на js но нещо не мога да се оправя ще съм много благодарен да помогнеш предполагам е нещо лесно,но ...
[Bulgarian_Racing_Community.zip](https://github.com/krisitown/pathfinder/files/9232561/Bulgarian_Racing_Community.zip)

**Comment by krisitown** [comment]
Бих те посъветвал да разделиш всеки article на отделна страница (например: /articles/1, /articles/2 и т.н.)
Така като са на една страница, всички id-та които използваш вече не са уникални, и джаваскрипта ти се закача само за първия успешно.

Ако държиш всички да са на една страница, то тогава може да запишеш размера на списъка в някой hidden element извън цикъла, а вътре в цикъла да добавяш id-то на article към id-то на елемента (например commentForm ще стане commentForm1, commentForm2, commentForm3). 

След това в comments.js като са заредени всички елементи можеш да итерираш от 0 до броя на article и за всеки да закачаш хендлър функция, на която подаваш и id-то на стаята.

Така функцията ще знае да селектне commentForm${articleId} и ще вземе информацията от нея, също и ще може да прати на АПИ-то на правилния път (отново иползвайки articleId). С чист джаваскрипт е малко дървено според мен, така че отново съветвам да си разделиш да има по един article на страница и вече /articles може да стане индекс страница.
